version: '3'

services:

  traefik:
    image: traefik:2.5
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`sampleapi`)
      - --entrypoints.sampleapi_http.address=:80
      - --entrypoints.sampleapi_https.address=:443
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - gateway
      - sampleapi

  rest-api:
    entrypoint: rest
    container_name: rest-api
    build: .
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=sampleapi"
      - "traefik.docker.network=sampleapi"
      - "traefik.http.services.sampleapi_rest.loadbalancer.server.port=80"
      #http
      - traefik.http.routers.sampleapi_rest_http.entrypoints=sampleapi_http
      - traefik.http.routers.sampleapi_rest_http.rule=PathPrefix(`/`)
      - traefik.http.routers.sampleapi_rest_http.service=sampleapi_rest
      # https
      - traefik.http.routers.sampleapi_rest_https.entrypoints=sampleapi_https
      - traefik.http.routers.sampleapi_rest_https.rule=PathPrefix(`/`)
      - traefik.http.routers.sampleapi_rest_https.service=sampleapi_rest
      - traefik.http.routers.sampleapi_rest_https.tls=true
    networks:
      - sampleapi
    ports:
      - "8001:80"
    env_file:
      - .env

  graphql-api:
    entrypoint: graphql
    container_name: graphql-api
    build: .
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=sampleapi"
      - "traefik.docker.network=sampleapi"
      - "traefik.http.services.sampleapi_graphql.loadbalancer.server.port=80"
      #http
      - traefik.http.routers.sampleapi_graphql_http.entrypoints=sampleapi_http
      - traefik.http.routers.sampleapi_graphql_http.rule=PathPrefix(`/`)
      - traefik.http.routers.sampleapi_graphql_http.service=sampleapi_graphql
      # https
      - traefik.http.routers.sampleapi_graphql_https.entrypoints=sampleapi_https
      - traefik.http.routers.sampleapi_graphql_https.rule=PathPrefix(`/`)
      - traefik.http.routers.sampleapi_graphql_https.service=sampleapi_graphql
      - traefik.http.routers.sampleapi_graphql_https.tls=true
    networks:
      - sampleapi
    ports:
      - "8002:80"
    env_file:
      - .env

  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sampleapi
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}

networks:
  gateway:
  sampleapi:

volumes:
  db-data: