version: '3'

services:

  api:
    build: .
    secrets:
      - db-password
    depends_on:
      - db
    ports:
      - 8005:8005
    env_file:
      - .env

  db:
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt